### ISSUE TITLE
Defining Time Dependent Lindblad operators

### ISSUE THREAD

**Issue by ivanshalashilin** [USCqserver/OpenQuantumTools.jl#96]
I am trying to solve an annealing problem with an open quantum system, as in [this letter](https://arxiv.org/pdf/2208.09068.pdf), equation 5,

$$
L_{\omega i}=\sum_{a, b} \delta_{\omega, E_b(s)-E_a(s)}\left\langle E_a(s)\left|\sigma_i^z\right| E_b(s)\right\rangle\left|E_a(s)\right\rangle\left\langle E_b(s)\right|
$$

i.e. it requires the use of time-dependent Lindblad operators. 

[The HOWST tutorial on Lindblad open systems](https://uscqserver.github.io/HOQSTTutorials.jl/html/introduction/02-lindblad_equation.html) states the `# the rate and Lindblad operator can also be time-dependent functions`. 

 What would be the best way of defining a general operator (and in this case $\gamma$) as a time-dependent function, then using that as the input for `Lindblad()`? The documentation only shows how to do this for Hamiltonians, and I can't seem to find anything in the docs that shows how to do this for a general operator. The closest I can find is [`OpenQuantumBase.TimeDependentCoupling`](https://docs.juliahub.com/OpenQuantumTools/iRrSZ/0.6.2/lib/coupling.html#OpenQuantumBase.TimeDependentCoupling), but this also isn't quite what i am looking for, since it's a time-dependent coefficient rather than the actual matrix being time dependent.

I am very new to Julia, so it might be something very obvious, but regardless thank you in advance.

**Comment by neversakura** [comment]
Eq. (5) in the paper you mentioned is called the adiabatic master equation (AME). You can use the direct interface described in this [tutorial](https://uscqserver.github.io/HOQSTTutorials.jl/html/introduction/03-single_qubit_ame.html) without the need to define your own t-dependent Lindblad operators. The solver will take care of the rest. 

A side note, to define a t-dependent Lindblad operator you can use
`Lindblad(gammaFunc, lFunc)` where `gammaFunc` and `lFunc` are your own functions which take a single input argument `s`  and return the $\gamma$ and $L$.

**Comment by neversakura** [comment]
Closing this issue if no further questions.
